### ISSUE TITLE
自己配了一遍，一直报错

### ISSUE THREAD

**Issue by sadpig1993** [zzz945/react-native-alibc-sdk#2]
![image](https://cloud.githubusercontent.com/assets/3955216/24963547/7ae55480-1fd1-11e7-9733-9b1f53b79e61.png)
![image](https://cloud.githubusercontent.com/assets/3955216/24963661/cbc3cf58-1fd1-11e7-96d0-88b1aea8612c.png)

ld: framework not found UTMini
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by zzz945** [comment]
有没有在build phase里将node_modules/react-native-alibc-sdk/ios/AlibcTradeSDK/Frameworks和Reaources全部加入工程以及demo工程的其它依赖加入

**Comment by sadpig1993** [comment]
frameworks和resource都引进去了，早上起来重新搭了一遍，搞定了。npm换成yarn之后就没问题了。
