### ISSUE TITLE
ios的webview可以换成push进入吗？

### ISSUE THREAD

**Issue by sadpig1993** [zzz945/react-native-alibc-sdk#3]
或者有没有办法可以用rn的webview显示百川sdk的页面
![image](https://cloud.githubusercontent.com/assets/3955216/25035567/e186893e-2120-11e7-80e3-2ac9835f7708.png)

**Comment by zzz945** [comment]
我有个想法，从native端写一个封装了webview的ui component， 到react native里这样用：
<TradeWebview itemid="8888888" />

**Comment by zzz945** [comment]
用native的web view显示淘宝页面， 并将这个native webview做成了rn 的component， 命名为AlibcTradeWebView。现在实现了android部分

**Comment by sadpig1993** [comment]
我把这个webview的itemId改成了url，打开一个url，类似
```
http://uland.taobao.com/coupon/edetail?activityId=13e9f56152bf43329f1940b7354c7bcf&pid=mm_33719122_5420449_75840102&itemId=543666118631&src=quanbaibai 
```
这个页面有个schema唤起，会唤起手淘~sdk的forceH5不管用了。于是想拦截webview所有的schema请求，但是这样子就没法唤起sdk的登录了。
现在想判断如果页面要转跳到https://login.m.taobao.com 就利用百川sdk直接唤起登录。因为Android和java能力有限，写到这里了就不会了。

![image](https://cloud.githubusercontent.com/assets/3955216/25072082/43918212-22f9-11e7-988c-e235c1f4c44d.png)


```
                      new WebViewClient() {
                            @Override
                            public boolean shouldOverrideUrlLoading(WebView view, String url) {
                                if(url.startsWith("http://") || url.startsWith("https://")) {
                                    if(url.startsWith("https://login.m.taobao.com")) {
                                        
                                        return false;
                                    } else {
                                        view.loadUrl(url);
                                    }
                                    return true;
                                } else {

                                    return false;
                                }
                            }
                        }
```

**Comment by sadpig1993** [comment]
另外，最好可以加上这个api，用sdk打开某个url。
感谢~~

**Comment by sadpig1993** [comment]
![image](https://cloud.githubusercontent.com/assets/3955216/25072491/1ae3f08a-2302-11e7-92cc-07a43995eaa9.png)
我拦截了去登录页的转跳，然后给rn了一个回调。然后用js再唤起登录

**Comment by zzz945** [comment]
现在可以从js里用AlibcTradeWebView打开某个url了，并且实现了goBack／goForward控制和onStateChange用户获取web view状态。并且，已经用如下代码屏蔽了除了https://login.m.taobao.com以外的内部跳转。
@Override
		public boolean shouldOverrideUrlLoading(WebView view, String url) {
			if (url.startsWith("http://login.m.taobao.com/") || url.startsWith("http://") || url.startsWith("https://") ||
				url.startsWith("file://")) {
				return false;
			} else {
				return true;
			}
		}

**Comment by sadpig1993** [comment]
嗯，看到了~超棒。
不过还有个小问题，webview里的网页title好像现在拿不到。

**Comment by sadpig1993** [comment]
另外，安卓webview打不开这个页面
https://h5.m.taobao.com/mlapp/olist.html

**Comment by zzz945** [comment]
android 打不开https://h5.m.taobao.com/mlapp/olist.html很奇怪， 我写了最小化的测试程序，直接用webview.loadurl都打不开。另外， 你支付回调后崩溃的问题解决了吗

**Comment by zzz945** [comment]
参考React native的WebView实现， 加了这行代码就可以显示orders页面了 
// Fixes broken full-screen modals/galleries due to body height being 0.
webView.setLayoutParams(
				new LayoutParams(LayoutParams.MATCH_PARENT,
					LayoutParams.MATCH_PARENT));
